// Plausibility norming study for Mechanical Turk.
// Created by Anna Namyst, 12/18/2015. Adapted by DM, 23/04/2020

var shuffleSequence   = seq("intro","setcounter","consent","demographics","instructions", 
                            "GuidedPractice1", "feedback1", "GuidedPractice2", "feedback2", "GuidedPractice3", "feedback3", "feedback4", 
                            sepWith("sep", "practice"), "endofpractice", 
                            sepWith("sep",randomize(rshuffle("a", "b", "c", "d", "e", "f", "g", "h","control"))),
                            "sr","code");

var practiceItemTypes = ["GuidedPractice1","GuidedPractice2","GuidedPractice3", "practice"];

var manualSendResults = true; 

var centerItems = true;


var defaults = [

    "Separator", {
        transfer: "keypress",
        normalMessage: "Press any key to continue",
    },


     "AcceptabilityJudgment", { as: ["1", "2", "3", "4", "5", "6", "7"],
                               presentAsScale: true,
                               instructions: "Use number keys or click boxes to answer.",
                               leftComment: "(very implausible)", rightComment: "(very plausible)" },

    "Message", {hideProgressBar: true},

    "Form", {
        hideProgressBar: true,
        continueOnReturn: true,
        saveReactionTime: true
    }
];


var items = [
   

    
    ["sr", "__SendResults__", { }],

    ["sep", "Separator", { }],

    ["setcounter","__SetCounter__",{}],

    ["instructions", "Message", {html: {include: "instructions.html"}}],

["consent", "Form", {html: {include: "consent_other.html"}}],

    ["intro", "Message", {html: {include: "welcome_other.html"}}],

    ["demographics", "Form", {
        html: {include: "demographic.html"},
        validators: {age: function (s) {if (s >= 18) return true; else return "Bad value for \u2018age\u2019";}
        }
    }],

 
    
//Guided Practice Items

["GuidedPractice1" , "AcceptabilityJudgment", {s: {html: "He drank the coffee."}}],
["feedback1", "Message", {html: {include:  "feedback1.html"}}],
["GuidedPractice2" , "AcceptabilityJudgment", {s: {html: "She ate the tree."}}],
["feedback2", "Message", {html: {include:  "feedback2.html"}}],
["GuidedPractice3" , "AcceptabilityJudgment", {s: {html:"He plowed the garden."}}],
["feedback3", "Message", {html: {include:  "feedback3.html"}}],
["feedback4", "Message", {html: {include:  "feedback4.html"}}],

    
// Short practice.
    
["practice" , "AcceptabilityJudgment", {s: {html: "He kicked the flower."}}],
["practice" , "AcceptabilityJudgment", {s: {html: "She conducted the experiment."}}],
["practice" , "AcceptabilityJudgment", {s: {html: "She fought the house."}}],     

    
//End of practice message.
    
["endofpractice", "Message", {html: "<p><i>This is the end of the practice session. We now show the experimental sentences. </i></p><br>" }],

    
//Debriefing with payment code.  
    
["code", "Message", {
    transfer: "keypress",
    consentRequired: false, 
    html: {include: "debriefing_other.html"} 
}],
    

//Experimental Items.
    
[['a',1] , 'AcceptabilityJudgment', {s: {html: 'He sailed the boat.'}}],
[['b',1] , 'AcceptabilityJudgment', {s: {html: 'He sailed the table.'}}],
[['c',1] , 'AcceptabilityJudgment', {s: {html: 'He sailed the sink.'}}],
[['d',1] , 'AcceptabilityJudgment', {s: {html: 'He sailed the truck.'}}],
[['e',1] , 'AcceptabilityJudgment', {s: {html: 'He fixed the boat.'}}],
[['f',1] , 'AcceptabilityJudgment', {s: {html: 'He fixed the table.'}}],
[['g',1] , 'AcceptabilityJudgment', {s: {html: 'He fixed the sink.'}}],
[['h',1] , 'AcceptabilityJudgment', {s: {html: 'He fixed the truck.'}}],
[['a',2] , 'AcceptabilityJudgment', {s: {html: 'She recommended the restaurant.'}}],
[['b',2] , 'AcceptabilityJudgment', {s: {html: 'She recommended the secret.'}}],
[['c',2] , 'AcceptabilityJudgment', {s: {html: 'She recommended the treasure.'}}],
[['d',2] , 'AcceptabilityJudgment', {s: {html: 'She recommended the cave.'}}],
[['e',2] , 'AcceptabilityJudgment', {s: {html: 'She discovered the restaurant.'}}],
[['f',2] , 'AcceptabilityJudgment', {s: {html: 'She discovered the secret.'}}],
[['g',2] , 'AcceptabilityJudgment', {s: {html: 'She discovered the treasure.'}}],
[['h',2] , 'AcceptabilityJudgment', {s: {html: 'She discovered the cave.'}}],
[['a',3] , 'AcceptabilityJudgment', {s: {html: 'She read the verse.'}}],
[['b',3] , 'AcceptabilityJudgment', {s: {html: 'She read the melody.'}}],
[['c',3] , 'AcceptabilityJudgment', {s: {html: 'She read the tune.'}}],
[['d',3] , 'AcceptabilityJudgment', {s: {html: 'She read the harmony.'}}],
[['e',3] , 'AcceptabilityJudgment', {s: {html: 'She hummed the verse.'}}],
[['f',3] , 'AcceptabilityJudgment', {s: {html: 'She hummed the melody.'}}],
[['g',3] , 'AcceptabilityJudgment', {s: {html: 'She hummed the tune.'}}],
[['h',3] , 'AcceptabilityJudgment', {s: {html: 'She hummed the harmony.'}}],
[['a',4] , 'AcceptabilityJudgment', {s: {html: 'She published the book.'}}],
[['b',4] , 'AcceptabilityJudgment', {s: {html: 'She published the car.'}}],
[['c',4] , 'AcceptabilityJudgment', {s: {html: 'She published the pen.'}}],
[['d',4] , 'AcceptabilityJudgment', {s: {html: 'She published the money.'}}],
[['e',4] , 'AcceptabilityJudgment', {s: {html: 'She borrowed the book.'}}],
[['f',4] , 'AcceptabilityJudgment', {s: {html: 'She borrowed the car.'}}],
[['g',4] , 'AcceptabilityJudgment', {s: {html: 'She borrowed the pen.'}}],
[['h',4] , 'AcceptabilityJudgment', {s: {html: 'She borrowed the money.'}}],
[['a',5] , 'AcceptabilityJudgment', {s: {html: 'He saw the hill.'}}],
[['b',5] , 'AcceptabilityJudgment', {s: {html: 'He saw the rock.'}}],
[['c',5] , 'AcceptabilityJudgment', {s: {html: 'He saw the ladder.'}}],
[['d',5] , 'AcceptabilityJudgment', {s: {html: 'He saw the mountain.'}}],
[['e',5] , 'AcceptabilityJudgment', {s: {html: 'He climbed the hill.'}}],
[['f',5] , 'AcceptabilityJudgment', {s: {html: 'He climbed the rock.'}}],
[['g',5] , 'AcceptabilityJudgment', {s: {html: 'He climbed the ladder.'}}],
[['h',5] , 'AcceptabilityJudgment', {s: {html: 'He climbed the mountain.'}}],
[['a',6] , 'AcceptabilityJudgment', {s: {html: 'He cut the wire.'}}],
[['b',6] , 'AcceptabilityJudgment', {s: {html: 'He cut the handle.'}}],
[['c',6] , 'AcceptabilityJudgment', {s: {html: 'He cut the trigger.'}}],
[['d',6] , 'AcceptabilityJudgment', {s: {html: 'He cut the plug.'}}],
[['e',6] , 'AcceptabilityJudgment', {s: {html: 'He pulled the wire.'}}],
[['f',6] , 'AcceptabilityJudgment', {s: {html: 'He pulled the handle.'}}],
[['g',6] , 'AcceptabilityJudgment', {s: {html: 'He pulled the trigger.'}}],
[['h',6] , 'AcceptabilityJudgment', {s: {html: 'He pulled the plug.'}}],
[['a',7] , 'AcceptabilityJudgment', {s: {html: 'She mowed the lawn.'}}],
[['b',7] , 'AcceptabilityJudgment', {s: {html: 'She mowed the flower.'}}],
[['c',7] , 'AcceptabilityJudgment', {s: {html: 'She mowed the plant.'}}],
[['d',7] , 'AcceptabilityJudgment', {s: {html: 'She mowed the tree.'}}],
[['e',7] , 'AcceptabilityJudgment', {s: {html: 'She watered the lawn.'}}],
[['f',7] , 'AcceptabilityJudgment', {s: {html: 'She watered the flower.'}}],
[['g',7] , 'AcceptabilityJudgment', {s: {html: 'She watered the plant.'}}],
[['h',7] , 'AcceptabilityJudgment', {s: {html: 'She watered the tree.'}}],
[['a',8] , 'AcceptabilityJudgment', {s: {html: 'He plowed the field.'}}],
[['b',8] , 'AcceptabilityJudgment', {s: {html: 'He plowed the restaurant.'}}],
[['c',8] , 'AcceptabilityJudgment', {s: {html: 'He plowed the apartment.'}}],
[['d',8] , 'AcceptabilityJudgment', {s: {html: 'He plowed the office.'}}],
[['e',8] , 'AcceptabilityJudgment', {s: {html: 'He leased the field.'}}],
[['f',8] , 'AcceptabilityJudgment', {s: {html: 'He leased the restaurant.'}}],
[['g',8] , 'AcceptabilityJudgment', {s: {html: 'He leased the apartment.'}}],
[['h',8] , 'AcceptabilityJudgment', {s: {html: 'He leased the office.'}}],
[['a',9] , 'AcceptabilityJudgment', {s: {html: 'He dropped the doll.'}}],
[['b',9] , 'AcceptabilityJudgment', {s: {html: 'He dropped the jeans.'}}],
[['c',9] , 'AcceptabilityJudgment', {s: {html: 'He dropped the stockings.'}}],
[['d',9] , 'AcceptabilityJudgment', {s: {html: 'He dropped the blouse.'}}],
[['e',9] , 'AcceptabilityJudgment', {s: {html: 'He ripped the doll.'}}],
[['f',9] , 'AcceptabilityJudgment', {s: {html: 'He ripped the jeans.'}}],
[['g',9] , 'AcceptabilityJudgment', {s: {html: 'He ripped the stockings.'}}],
[['h',9] , 'AcceptabilityJudgment', {s: {html: 'He ripped the blouse.'}}],
[['a',10] , 'AcceptabilityJudgment', {s: {html: 'She wore the dress.'}}],
[['b',10] , 'AcceptabilityJudgment', {s: {html: 'She wore the paper.'}}],
[['c',10] , 'AcceptabilityJudgment', {s: {html: 'She wore the sheet.'}}],
[['d',10] , 'AcceptabilityJudgment', {s: {html: 'She wore the napkin.'}}],
[['e',10] , 'AcceptabilityJudgment', {s: {html: 'She tore the dress.'}}],
[['f',10] , 'AcceptabilityJudgment', {s: {html: 'She tore the paper.'}}],
[['g',10] , 'AcceptabilityJudgment', {s: {html: 'She tore the sheet.'}}],
[['h',10] , 'AcceptabilityJudgment', {s: {html: 'She tore the napkin.'}}],
[['a',11] , 'AcceptabilityJudgment', {s: {html: 'He added the mixture.'}}],
[['b',11] , 'AcceptabilityJudgment', {s: {html: 'He added the drink.'}}],
[['c',11] , 'AcceptabilityJudgment', {s: {html: 'He added the smoothie.'}}],
[['d',11] , 'AcceptabilityJudgment', {s: {html: 'He added the soup.'}}],
[['e',11] , 'AcceptabilityJudgment', {s: {html: 'He stirred the mixture.'}}],
[['f',11] , 'AcceptabilityJudgment', {s: {html: 'He stirred the drink.'}}],
[['g',11] , 'AcceptabilityJudgment', {s: {html: 'He stirred the smoothie.'}}],
[['h',11] , 'AcceptabilityJudgment', {s: {html: 'He stirred the soup.'}}],
[['a',12] , 'AcceptabilityJudgment', {s: {html: 'He refereed the game.'}}],
[['b',12] , 'AcceptabilityJudgment', {s: {html: 'He refereed the festival.'}}],
[['c',12] , 'AcceptabilityJudgment', {s: {html: 'He refereed the concert.'}}],
[['d',12] , 'AcceptabilityJudgment', {s: {html: 'He refereed the interview.'}}],
[['e',12] , 'AcceptabilityJudgment', {s: {html: 'He organized the game.'}}],
[['f',12] , 'AcceptabilityJudgment', {s: {html: 'He organized the festival.'}}],
[['g',12] , 'AcceptabilityJudgment', {s: {html: 'He organized the concert.'}}],
[['h',12] , 'AcceptabilityJudgment', {s: {html: 'He organized the interview.'}}],
[['a',13] , 'AcceptabilityJudgment', {s: {html: 'He applied the ointment.'}}],
[['b',13] , 'AcceptabilityJudgment', {s: {html: 'He applied the pill.'}}],
[['c',13] , 'AcceptabilityJudgment', {s: {html: 'He applied the drug.'}}],
[['d',13] , 'AcceptabilityJudgment', {s: {html: 'He applied the rest.'}}],
[['e',13] , 'AcceptabilityJudgment', {s: {html: 'He prescribed the ointment.'}}],
[['f',13] , 'AcceptabilityJudgment', {s: {html: 'He prescribed the pill.'}}],
[['g',13] , 'AcceptabilityJudgment', {s: {html: 'He prescribed the drug.'}}],
[['h',13] , 'AcceptabilityJudgment', {s: {html: 'He prescribed rest.'}}],
[['a',14] , 'AcceptabilityJudgment', {s: {html: 'He rehearsed the play.'}}],
[['b',14] , 'AcceptabilityJudgment', {s: {html: 'He rehearsed the letter.'}}],
[['c',14] , 'AcceptabilityJudgment', {s: {html: 'He rehearsed the book.'}}],
[['d',14] , 'AcceptabilityJudgment', {s: {html: 'He rehearsed the message.'}}],
[['e',14] , 'AcceptabilityJudgment', {s: {html: 'He wrote the play.'}}],
[['f',14] , 'AcceptabilityJudgment', {s: {html: 'He wrote the letter.'}}],
[['g',14] , 'AcceptabilityJudgment', {s: {html: 'He wrote the book.'}}],
[['h',14] , 'AcceptabilityJudgment', {s: {html: 'He wrote the message.'}}],
[['a',15] , 'AcceptabilityJudgment', {s: {html: 'He snapped the picture.'}}],
[['b',15] , 'AcceptabilityJudgment', {s: {html: 'He snapped the portrait.'}}],
[['c',15] , 'AcceptabilityJudgment', {s: {html: 'He snapped the wall.'}}],
[['d',15] , 'AcceptabilityJudgment', {s: {html: 'He snapped the fence.'}}],
[['e',15] , 'AcceptabilityJudgment', {s: {html: 'He painted the picture.'}}],
[['f',15] , 'AcceptabilityJudgment', {s: {html: 'He painted the portrait.'}}],
[['g',15] , 'AcceptabilityJudgment', {s: {html: 'He painted the wall.'}}],
[['h',15] , 'AcceptabilityJudgment', {s: {html: 'He painted the fence.'}}],
[['a',16] , 'AcceptabilityJudgment', {s: {html: 'He pushed the sculpture.'}}],
[['b',16] , 'AcceptabilityJudgment', {s: {html: 'He pushed the artwork.'}}],
[['c',16] , 'AcceptabilityJudgment', {s: {html: 'He pushed the fruit.'}}],
[['d',16] , 'AcceptabilityJudgment', {s: {html: 'He pushed the fossil.'}}],
[['e',16] , 'AcceptabilityJudgment', {s: {html: 'He preserved the sculpture.'}}],
[['f',16] , 'AcceptabilityJudgment', {s: {html: 'He preserved the artwork.'}}],
[['g',16] , 'AcceptabilityJudgment', {s: {html: 'He preserved the fruit.'}}],
[['h',16] , 'AcceptabilityJudgment', {s: {html: 'He preserved the fossil.'}}],
[['a',17] , 'AcceptabilityJudgment', {s: {html: 'He fluffed the towel.'}}],
[['b',17] , 'AcceptabilityJudgment', {s: {html: 'He fluffed the sheet.'}}],
[['c',17] , 'AcceptabilityJudgment', {s: {html: 'He fluffed the tablecloth.'}}],
[['d',17] , 'AcceptabilityJudgment', {s: {html: 'He fluffed the shirt.'}}],
[['e',17] , 'AcceptabilityJudgment', {s: {html: 'He dried the towel.'}}],
[['f',17] , 'AcceptabilityJudgment', {s: {html: 'He dried the sheet.'}}],
[['g',17] , 'AcceptabilityJudgment', {s: {html: 'He dried the tablecloth.'}}],
[['h',17] , 'AcceptabilityJudgment', {s: {html: 'He dried the shirt.'}}],
[['a',18] , 'AcceptabilityJudgment', {s: {html: 'He unplugged the printer.'}}],
[['b',18] , 'AcceptabilityJudgment', {s: {html: 'He unplugged the bike.'}}],
[['c',18] , 'AcceptabilityJudgment', {s: {html: 'He unplugged the shed.'}}],
[['d',18] , 'AcceptabilityJudgment', {s: {html: 'He unplugged the roof.'}}],
[['e',18] , 'AcceptabilityJudgment', {s: {html: 'He repaired the printer.'}}],
[['f',18] , 'AcceptabilityJudgment', {s: {html: 'He repaired the bike.'}}],
[['g',18] , 'AcceptabilityJudgment', {s: {html: 'He repaired the shed.'}}],
[['h',18] , 'AcceptabilityJudgment', {s: {html: 'He repaired the roof.'}}],
[['a',19] , 'AcceptabilityJudgment', {s: {html: 'He sold the closet.'}}],
[['b',19] , 'AcceptabilityJudgment', {s: {html: 'He sold the door.'}}],
[['c',19] , 'AcceptabilityJudgment', {s: {html: 'He sold the safe.'}}],
[['d',19] , 'AcceptabilityJudgment', {s: {html: 'He sold the cubicle.'}}],
[['e',19] , 'AcceptabilityJudgment', {s: {html: 'He locked the closet.'}}],
[['f',19] , 'AcceptabilityJudgment', {s: {html: 'He locked the door.'}}],
[['g',19] , 'AcceptabilityJudgment', {s: {html: 'He locked the safe.'}}],
[['h',19] , 'AcceptabilityJudgment', {s: {html: 'He locked the cubicle.'}}],
[['a',20] , 'AcceptabilityJudgment', {s: {html: 'He drove the scooter.'}}],
[['b',20] , 'AcceptabilityJudgment', {s: {html: 'He drove the computer.'}}],
[['c',20] , 'AcceptabilityJudgment', {s: {html: 'He drove the drone.'}}],
[['d',20] , 'AcceptabilityJudgment', {s: {html: 'He drove the aircraft.'}}],
[['e',20] , 'AcceptabilityJudgment', {s: {html: 'He crashed the scooter.'}}],
[['f',20] , 'AcceptabilityJudgment', {s: {html: 'He crashed the computer.'}}],
[['g',20] , 'AcceptabilityJudgment', {s: {html: 'He crashed the drone.'}}],
[['h',20] , 'AcceptabilityJudgment', {s: {html: 'He crashed the aircraft.'}}],
[['a',21] , 'AcceptabilityJudgment', {s: {html: 'He left the laptop.'}}],
[['b',21] , 'AcceptabilityJudgment', {s: {html: 'He left the television.'}}],
[['c',21] , 'AcceptabilityJudgment', {s: {html: 'He left the radio.'}}],
[['d',21] , 'AcceptabilityJudgment', {s: {html: 'He left the lamp.'}}],
[['e',21] , 'AcceptabilityJudgment', {s: {html: 'He unplugged the laptop.'}}],
[['f',21] , 'AcceptabilityJudgment', {s: {html: 'He unplugged the television.'}}],
[['g',21] , 'AcceptabilityJudgment', {s: {html: 'He unplugged the radio.'}}],
[['h',21] , 'AcceptabilityJudgment', {s: {html: 'He unplugged the lamp.'}}],
[['a',22] , 'AcceptabilityJudgment', {s: {html: 'He brewed the coffee.'}}],
[['b',22] , 'AcceptabilityJudgment', {s: {html: 'He brewed the water.'}}],
[['c',22] , 'AcceptabilityJudgment', {s: {html: 'He brewed the wine.'}}],
[['d',22] , 'AcceptabilityJudgment', {s: {html: 'He brewed the juice.'}}],
[['e',22] , 'AcceptabilityJudgment', {s: {html: 'He spilled the coffee.'}}],
[['f',22] , 'AcceptabilityJudgment', {s: {html: 'He spilled the water.'}}],
[['g',22] , 'AcceptabilityJudgment', {s: {html: 'He spilled the wine.'}}],
[['h',22] , 'AcceptabilityJudgment', {s: {html: 'He spilled the juice.'}}],
[['a',23] , 'AcceptabilityJudgment', {s: {html: 'He found the treasure.'}}],
[['b',23] , 'AcceptabilityJudgment', {s: {html: 'He found the bone.'}}],
[['c',23] , 'AcceptabilityJudgment', {s: {html: 'He found the chest.'}}],
[['d',23] , 'AcceptabilityJudgment', {s: {html: 'He found the casket.'}}],
[['e',23] , 'AcceptabilityJudgment', {s: {html: 'He buried the treasure.'}}],
[['f',23] , 'AcceptabilityJudgment', {s: {html: 'He buried the bone.'}}],
[['g',23] , 'AcceptabilityJudgment', {s: {html: 'He buried the chest.'}}],
[['h',23] , 'AcceptabilityJudgment', {s: {html: 'He buried the casket.'}}],
[['a',24] , 'AcceptabilityJudgment', {s: {html: 'She discovered the candle.'}}],
[['b',24] , 'AcceptabilityJudgment', {s: {html: 'She discovered the fire.'}}],
[['c',24] , 'AcceptabilityJudgment', {s: {html: 'She discovered the incense.'}}],
[['d',24] , 'AcceptabilityJudgment', {s: {html: 'She discovered the cigarette.'}}],
[['e',24] , 'AcceptabilityJudgment', {s: {html: 'She lit the candle.'}}],
[['f',24] , 'AcceptabilityJudgment', {s: {html: 'She lit the fire.'}}],
[['g',24] , 'AcceptabilityJudgment', {s: {html: 'She lit the incense.'}}],
[['h',24] , 'AcceptabilityJudgment', {s: {html: 'She lit the cigarette.'}}],
[['a',25] , 'AcceptabilityJudgment', {s: {html: 'She chose the makeup.'}}],
[['b',25] , 'AcceptabilityJudgment', {s: {html: 'She chose the key.'}}],
[['c',25] , 'AcceptabilityJudgment', {s: {html: 'She chose the wallet.'}}],
[['d',25] , 'AcceptabilityJudgment', {s: {html: 'She chose the glasses.'}}],
[['e',25] , 'AcceptabilityJudgment', {s: {html: 'She misplaced the makeup.'}}],
[['f',25] , 'AcceptabilityJudgment', {s: {html: 'She misplaced the key.'}}],
[['g',25] , 'AcceptabilityJudgment', {s: {html: 'She misplaced the wallet.'}}],
[['h',25] , 'AcceptabilityJudgment', {s: {html: 'She misplaced the glasses.'}}],
[['a',26] , 'AcceptabilityJudgment', {s: {html: 'She hurt the muscle.'}}],
[['b',26] , 'AcceptabilityJudgment', {s: {html: 'She hurt the tights.'}}],
[['c',26] , 'AcceptabilityJudgment', {s: {html: 'She hurt the pants.'}}],
[['d',26] , 'AcceptabilityJudgment', {s: {html: 'She hurt the vest.'}}],
[['e',26] , 'AcceptabilityJudgment', {s: {html: 'She tore the muscle.'}}],
[['f',26] , 'AcceptabilityJudgment', {s: {html: 'She tore the tights.'}}],
[['g',26] , 'AcceptabilityJudgment', {s: {html: 'She tore the pants.'}}],
[['h',26] , 'AcceptabilityJudgment', {s: {html: 'She tore the vest.'}}],
[['a',27] , 'AcceptabilityJudgment', {s: {html: 'She rode the train.'}}],
[['b',27] , 'AcceptabilityJudgment', {s: {html: 'She rode the appointment.'}}],
[['c',27] , 'AcceptabilityJudgment', {s: {html: 'She rode the meeting.'}}],
[['d',27] , 'AcceptabilityJudgment', {s: {html: 'She rode the lecture.'}}],
[['e',27] , 'AcceptabilityJudgment', {s: {html: 'She missed the train.'}}],
[['f',27] , 'AcceptabilityJudgment', {s: {html: 'She missed the appointment.'}}],
[['g',27] , 'AcceptabilityJudgment', {s: {html: 'She missed the meeting.'}}],
[['h',27] , 'AcceptabilityJudgment', {s: {html: 'She missed the lecture.'}}],
[['a',28] , 'AcceptabilityJudgment', {s: {html: 'He moved the board.'}}],
[['b',28] , 'AcceptabilityJudgment', {s: {html: 'He moved the bathroom.'}}],
[['c',28] , 'AcceptabilityJudgment', {s: {html: 'He moved the floor.'}}],
[['d',28] , 'AcceptabilityJudgment', {s: {html: 'He moved the kitchen.'}}],
[['e',28] , 'AcceptabilityJudgment', {s: {html: 'He cleaned the board.'}}],
[['f',28] , 'AcceptabilityJudgment', {s: {html: 'He cleaned the bathroom.'}}],
[['g',28] , 'AcceptabilityJudgment', {s: {html: 'He cleaned the floor.'}}],
[['h',28] , 'AcceptabilityJudgment', {s: {html: 'He cleaned the kitchen.'}}],
[['a',29] , 'AcceptabilityJudgment', {s: {html: 'She declined the award.'}}],
[['b',29] , 'AcceptabilityJudgment', {s: {html: 'She declined the race.'}}],
[['c',29] , 'AcceptabilityJudgment', {s: {html: 'She declined the prize.'}}],
[['d',29] , 'AcceptabilityJudgment', {s: {html: 'She declined the lottery.'}}],
[['e',29] , 'AcceptabilityJudgment', {s: {html: 'She won the award.'}}],
[['f',29] , 'AcceptabilityJudgment', {s: {html: 'She won the race.'}}],
[['g',29] , 'AcceptabilityJudgment', {s: {html: 'She won the prize.'}}],
[['h',29] , 'AcceptabilityJudgment', {s: {html: 'She won the lottery.'}}],
[['a',30] , 'AcceptabilityJudgment', {s: {html: 'She shared the bottle.'}}],
[['b',30] , 'AcceptabilityJudgment', {s: {html: 'She shared the plate.'}}],
[['c',30] , 'AcceptabilityJudgment', {s: {html: 'She shared the glass.'}}],
[['d',30] , 'AcceptabilityJudgment', {s: {html: 'She shared the dishwasher.'}}],
[['e',30] , 'AcceptabilityJudgment', {s: {html: 'She emptied the bottle.'}}],
[['f',30] , 'AcceptabilityJudgment', {s: {html: 'She emptied the plate.'}}],
[['g',30] , 'AcceptabilityJudgment', {s: {html: 'She emptied the glass.'}}],
[['h',30] , 'AcceptabilityJudgment', {s: {html: 'She emptied the dishwasher.'}}],
[['a',31] , 'AcceptabilityJudgment', {s: {html: 'He harvested the corn.'}}],
[['b',31] , 'AcceptabilityJudgment', {s: {html: 'He harvested the soup.'}}],
[['c',31] , 'AcceptabilityJudgment', {s: {html: 'He harvested the turkey.'}}],
[['d',31] , 'AcceptabilityJudgment', {s: {html: 'He harvested the dinner.'}}],
[['e',31] , 'AcceptabilityJudgment', {s: {html: 'He cooked the corn.'}}],
[['f',31] , 'AcceptabilityJudgment', {s: {html: 'He cooked the soup.'}}],
[['g',31] , 'AcceptabilityJudgment', {s: {html: 'He cooked the turkey.'}}],
[['h',31] , 'AcceptabilityJudgment', {s: {html: 'He cooked the dinner.'}}],
[['a',32] , 'AcceptabilityJudgment', {s: {html: 'She fabricated the story.'}}],
[['b',32] , 'AcceptabilityJudgment', {s: {html: 'She fabricated the letter.'}}],
[['c',32] , 'AcceptabilityJudgment', {s: {html: 'She fabricated the poem.'}}],
[['d',32] , 'AcceptabilityJudgment', {s: {html: 'She fabricated the novel.'}}],
[['e',32] , 'AcceptabilityJudgment', {s: {html: 'She wrote the story.'}}],
[['f',32] , 'AcceptabilityJudgment', {s: {html: 'She wrote the letter.'}}],
[['g',32] , 'AcceptabilityJudgment', {s: {html: 'She wrote the poem.'}}],
[['h',32] , 'AcceptabilityJudgment', {s: {html: 'She wrote the novel.'}}],
[['a',33] , 'AcceptabilityJudgment', {s: {html: 'She presented the sweater.'}}],
[['b',33] , 'AcceptabilityJudgment', {s: {html: 'She presented the necklace.'}}],
[['c',33] , 'AcceptabilityJudgment', {s: {html: 'She presented the ring.'}}],
[['d',33] , 'AcceptabilityJudgment', {s: {html: 'She presented the bracelet.'}}],
[['e',33] , 'AcceptabilityJudgment', {s: {html: 'She wore the sweater.'}}],
[['f',33] , 'AcceptabilityJudgment', {s: {html: 'She wore the necklace.'}}],
[['g',33] , 'AcceptabilityJudgment', {s: {html: 'She wore the ring.'}}],
[['h',33] , 'AcceptabilityJudgment', {s: {html: 'She wore the bracelet.'}}],
[['a',34] , 'AcceptabilityJudgment', {s: {html: 'He kneaded the dough.'}}],
[['b',34] , 'AcceptabilityJudgment', {s: {html: 'He kneaded the cake.'}}],
[['c',34] , 'AcceptabilityJudgment', {s: {html: 'He kneaded the jam.'}}],
[['d',34] , 'AcceptabilityJudgment', {s: {html: 'He kneaded the sauce.'}}],
[['e',34] , 'AcceptabilityJudgment', {s: {html: 'He tasted the dough.'}}],
[['f',34] , 'AcceptabilityJudgment', {s: {html: 'He tasted the cake.'}}],
[['g',34] , 'AcceptabilityJudgment', {s: {html: 'He tasted the jam.'}}],
[['h',34] , 'AcceptabilityJudgment', {s: {html: 'He tasted the sauce.'}}],
[['a',35] , 'AcceptabilityJudgment', {s: {html: 'He climbed the rope.'}}],
[['b',35] , 'AcceptabilityJudgment', {s: {html: 'He climbed the knot.'}}],
[['c',35] , 'AcceptabilityJudgment', {s: {html: 'He climbed the bow.'}}],
[['d',35] , 'AcceptabilityJudgment', {s: {html: 'He climbed the necktie.'}}],
[['e',35] , 'AcceptabilityJudgment', {s: {html: 'He tied the rope.'}}],
[['f',35] , 'AcceptabilityJudgment', {s: {html: 'He tied the knot.'}}],
[['g',35] , 'AcceptabilityJudgment', {s: {html: 'He tied the bow.'}}],
[['h',35] , 'AcceptabilityJudgment', {s: {html: 'He tied the necktie.'}}],
[['a',36] , 'AcceptabilityJudgment', {s: {html: 'She hid the toy.'}}],
[['b',36] , 'AcceptabilityJudgment', {s: {html: 'She hid the boomerang.'}}],
[['c',36] , 'AcceptabilityJudgment', {s: {html: 'She hid the ball.'}}],
[['d',36] , 'AcceptabilityJudgment', {s: {html: 'She hid the stick.'}}],
[['e',36] , 'AcceptabilityJudgment', {s: {html: 'She threw the toy.'}}],
[['f',36] , 'AcceptabilityJudgment', {s: {html: 'She threw the boomerang.'}}],
[['g',36] , 'AcceptabilityJudgment', {s: {html: 'She threw the ball.'}}],
[['h',36] , 'AcceptabilityJudgment', {s: {html: 'She threw the stick.'}}],
[['a',37] , 'AcceptabilityJudgment', {s: {html: 'He took the cigarette.'}}],
[['b',37] , 'AcceptabilityJudgment', {s: {html: 'He took the book.'}}],
[['c',37] , 'AcceptabilityJudgment', {s: {html: 'He took the record.'}}],
[['d',37] , 'AcceptabilityJudgment', {s: {html: 'He took the drill.'}}],
[['e',37] , 'AcceptabilityJudgment', {s: {html: 'He borrowed the cigarette.'}}],
[['f',37] , 'AcceptabilityJudgment', {s: {html: 'He borrowed the book.'}}],
[['g',37] , 'AcceptabilityJudgment', {s: {html: 'He borrowed the record.'}}],
[['h',37] , 'AcceptabilityJudgment', {s: {html: 'He borrowed the drill.'}}],
[['a',38] , 'AcceptabilityJudgment', {s: {html: 'He shredded the guitar.'}}],
[['b',38] , 'AcceptabilityJudgment', {s: {html: 'He shredded the instrument.'}}],
[['c',38] , 'AcceptabilityJudgment', {s: {html: 'He shredded the game.'}}],
[['d',38] , 'AcceptabilityJudgment', {s: {html: 'He shredded the song.'}}],
[['e',38] , 'AcceptabilityJudgment', {s: {html: 'He played the guitar.'}}],
[['f',38] , 'AcceptabilityJudgment', {s: {html: 'He played the instrument.'}}],
[['g',38] , 'AcceptabilityJudgment', {s: {html: 'He played the game.'}}],
[['h',38] , 'AcceptabilityJudgment', {s: {html: 'He played the song.'}}],
[['a',39] , 'AcceptabilityJudgment', {s: {html: 'She proved the equation.'}}],
[['b',39] , 'AcceptabilityJudgment', {s: {html: 'She proved the puzzle.'}}],
[['c',39] , 'AcceptabilityJudgment', {s: {html: 'She proved the riddle.'}}],
[['d',39] , 'AcceptabilityJudgment', {s: {html: 'She proved the problem.'}}],
[['e',39] , 'AcceptabilityJudgment', {s: {html: 'She solved the equation.'}}],
[['f',39] , 'AcceptabilityJudgment', {s: {html: 'She solved the puzzle.'}}],
[['g',39] , 'AcceptabilityJudgment', {s: {html: 'She solved the riddle.'}}],
[['h',39] , 'AcceptabilityJudgment', {s: {html: 'She solved the problem.'}}],
[['a',40] , 'AcceptabilityJudgment', {s: {html: 'She shattered the mirror.'}}],
[['b',40] , 'AcceptabilityJudgment', {s: {html: 'She shattered the shoe.'}}],
[['c',40] , 'AcceptabilityJudgment', {s: {html: 'She shattered the spoon.'}}],
[['d',40] , 'AcceptabilityJudgment', {s: {html: 'She shattered the belt.'}}],
[['e',40] , 'AcceptabilityJudgment', {s: {html: 'She polished the mirror.'}}],
[['f',40] , 'AcceptabilityJudgment', {s: {html: 'She polished the shoe.'}}],
[['g',40] , 'AcceptabilityJudgment', {s: {html: 'She polished the spoon.'}}],
[['h',40] , 'AcceptabilityJudgment', {s: {html: 'She polished the belt.'}}],
[['a',41] , 'AcceptabilityJudgment', {s: {html: 'She placed the chair.'}}],
[['b',41] , 'AcceptabilityJudgment', {s: {html: 'She placed the table.'}}],
[['c',41] , 'AcceptabilityJudgment', {s: {html: 'She placed the fence.'}}],
[['d',41] , 'AcceptabilityJudgment', {s: {html: 'She placed the cupboard.'}}],
[['e',41] , 'AcceptabilityJudgment', {s: {html: 'She varnished the chair.'}}],
[['f',41] , 'AcceptabilityJudgment', {s: {html: 'She varnished the table.'}}],
[['g',41] , 'AcceptabilityJudgment', {s: {html: 'She varnished the fence.'}}],
[['h',41] , 'AcceptabilityJudgment', {s: {html: 'She varnished the cupboard.'}}],
[['a',42] , 'AcceptabilityJudgment', {s: {html: 'She presented the painting.'}}],
[['b',42] , 'AcceptabilityJudgment', {s: {html: 'She presented the building.'}}],
[['c',42] , 'AcceptabilityJudgment', {s: {html: 'She presented the vehicle.'}}],
[['d',42] , 'AcceptabilityJudgment', {s: {html: 'She presented the window.'}}],
[['e',42] , 'AcceptabilityJudgment', {s: {html: 'She destroyed the painting.'}}],
[['f',42] , 'AcceptabilityJudgment', {s: {html: 'She destroyed the building.'}}],
[['g',42] , 'AcceptabilityJudgment', {s: {html: 'She destroyed the vehicle.'}}],
[['h',42] , 'AcceptabilityJudgment', {s: {html: 'She destroyed the window.'}}],
[['a',43] , 'AcceptabilityJudgment', {s: {html: 'He built the bookcase.'}}],
[['b',43] , 'AcceptabilityJudgment', {s: {html: 'He built the pizza.'}}],
[['c',43] , 'AcceptabilityJudgment', {s: {html: 'He built the mail.'}}],
[['d',43] , 'AcceptabilityJudgment', {s: {html: 'He built the speech.'}}],
[['e',43] , 'AcceptabilityJudgment', {s: {html: 'He delivered the bookcase.'}}],
[['f',43] , 'AcceptabilityJudgment', {s: {html: 'He delivered the pizza.'}}],
[['g',43] , 'AcceptabilityJudgment', {s: {html: 'He delivered the mail.'}}],
[['h',43] , 'AcceptabilityJudgment', {s: {html: 'He delivered the speech.'}}],
[['a',44] , 'AcceptabilityJudgment', {s: {html: 'She decorated the cake.'}}],
[['b',44] , 'AcceptabilityJudgment', {s: {html: 'She decorated the bread.'}}],
[['c',44] , 'AcceptabilityJudgment', {s: {html: 'She decorated the cookie.'}}],
[['d',44] , 'AcceptabilityJudgment', {s: {html: 'She decorated the loaf.'}}],
[['e',44] , 'AcceptabilityJudgment', {s: {html: 'She baked the cake.'}}],
[['f',44] , 'AcceptabilityJudgment', {s: {html: 'She baked the bread.'}}],
[['g',44] , 'AcceptabilityJudgment', {s: {html: 'She baked the cookie.'}}],
[['h',44] , 'AcceptabilityJudgment', {s: {html: 'She baked the loaf.'}}],
[['a',45] , 'AcceptabilityJudgment', {s: {html: 'He sewed the dress.'}}],
[['b',45] , 'AcceptabilityJudgment', {s: {html: 'He sewed the homepage.'}}],
[['c',45] , 'AcceptabilityJudgment', {s: {html: 'He sewed the poster.'}}],
[['d',45] , 'AcceptabilityJudgment', {s: {html: 'He sewed the flyer.'}}],
[['e',45] , 'AcceptabilityJudgment', {s: {html: 'He designed the dress.'}}],
[['f',45] , 'AcceptabilityJudgment', {s: {html: 'He designed the homepage.'}}],
[['g',45] , 'AcceptabilityJudgment', {s: {html: 'He designed the poster.'}}],
[['h',45] , 'AcceptabilityJudgment', {s: {html: 'He designed the flyer.'}}],
[['a',46] , 'AcceptabilityJudgment', {s: {html: 'He hid the console.'}}],
[['b',46] , 'AcceptabilityJudgment', {s: {html: 'He hid the guitar.'}}],
[['c',46] , 'AcceptabilityJudgment', {s: {html: 'He hid the piano.'}}],
[['d',46] , 'AcceptabilityJudgment', {s: {html: 'He hid the bass.'}}],
[['e',46] , 'AcceptabilityJudgment', {s: {html: 'He played the console.'}}],
[['f',46] , 'AcceptabilityJudgment', {s: {html: 'He played the guitar.'}}],
[['g',46] , 'AcceptabilityJudgment', {s: {html: 'He played the piano.'}}],
[['h',46] , 'AcceptabilityJudgment', {s: {html: 'He played the bass.'}}],
[['a',47] , 'AcceptabilityJudgment', {s: {html: 'She wrote the poem.'}}],
[['b',47] , 'AcceptabilityJudgment', {s: {html: 'She wrote the device.'}}],
[['c',47] , 'AcceptabilityJudgment', {s: {html: 'She wrote the game.'}}],
[['d',47] , 'AcceptabilityJudgment', {s: {html: 'She wrote the robot.'}}],
[['e',47] , 'AcceptabilityJudgment', {s: {html: 'She invented the poem.'}}],
[['f',47] , 'AcceptabilityJudgment', {s: {html: 'She invented the device.'}}],
[['g',47] , 'AcceptabilityJudgment', {s: {html: 'She invented the game.'}}],
[['h',47] , 'AcceptabilityJudgment', {s: {html: 'She invented the robot.'}}],
[['a',48] , 'AcceptabilityJudgment', {s: {html: 'She developed the project.'}}],
[['b',48] , 'AcceptabilityJudgment', {s: {html: 'She developed the toast.'}}],
[['c',48] , 'AcceptabilityJudgment', {s: {html: 'She developed the plan.'}}],
[['d',48] , 'AcceptabilityJudgment', {s: {html: 'She developed the marriage.'}}],
[['e',48] , 'AcceptabilityJudgment', {s: {html: 'She proposed the project.'}}],
[['f',48] , 'AcceptabilityJudgment', {s: {html: 'She proposed the toast.'}}],
[['g',48] , 'AcceptabilityJudgment', {s: {html: 'She proposed the plan.'}}],
[['h',48] , 'AcceptabilityJudgment', {s: {html: 'She proposed the marriage.'}}],
[['a',49] , 'AcceptabilityJudgment', {s: {html: 'He pursued the role.'}}],
[['b',49] , 'AcceptabilityJudgment', {s: {html: 'He pursued the speech.'}}],
[['c',49] , 'AcceptabilityJudgment', {s: {html: 'He pursued the song.'}}],
[['d',49] , 'AcceptabilityJudgment', {s: {html: 'He pursued the performance.'}}],
[['e',49] , 'AcceptabilityJudgment', {s: {html: 'He rehearsed the role.'}}],
[['f',49] , 'AcceptabilityJudgment', {s: {html: 'He rehearsed the speech.'}}],
[['g',49] , 'AcceptabilityJudgment', {s: {html: 'He rehearsed the song.'}}],
[['h',49] , 'AcceptabilityJudgment', {s: {html: 'He rehearsed the performance.'}}],
[['a',50] , 'AcceptabilityJudgment', {s: {html: 'He organized the concert.'}}],
[['b',50] , 'AcceptabilityJudgment', {s: {html: 'He organized the church.'}}],
[['c',50] , 'AcceptabilityJudgment', {s: {html: 'He organized the school.'}}],
[['d',50] , 'AcceptabilityJudgment', {s: {html: 'He organized the lecture.'}}],
[['e',50] , 'AcceptabilityJudgment', {s: {html: 'He attended the concert.'}}],
[['f',50] , 'AcceptabilityJudgment', {s: {html: 'He attended the church.'}}],
[['g',50] , 'AcceptabilityJudgment', {s: {html: 'He attended the school.'}}],
[['h',50] , 'AcceptabilityJudgment', {s: {html: 'He attended the lecture.'}}],
[['a',51] , 'AcceptabilityJudgment', {s: {html: 'She gave the speech.'}}],
[['b',51] , 'AcceptabilityJudgment', {s: {html: 'She gave the letter.'}}],
[['c',51] , 'AcceptabilityJudgment', {s: {html: 'She gave the prose.'}}],
[['d',51] , 'AcceptabilityJudgment', {s: {html: 'She gave the email.'}}],
[['e',51] , 'AcceptabilityJudgment', {s: {html: 'She wrote the speech.'}}],
[['f',51] , 'AcceptabilityJudgment', {s: {html: 'She wrote the letter.'}}],
[['g',51] , 'AcceptabilityJudgment', {s: {html: 'She wrote the prose.'}}],
[['h',51] , 'AcceptabilityJudgment', {s: {html: 'She wrote the email.'}}],
[['a',52] , 'AcceptabilityJudgment', {s: {html: 'He washed the t-shirt.'}}],
[['b',52] , 'AcceptabilityJudgment', {s: {html: 'He washed the apartment.'}}],
[['c',52] , 'AcceptabilityJudgment', {s: {html: 'He washed the watch.'}}],
[['d',52] , 'AcceptabilityJudgment', {s: {html: 'He washed the jewelry.'}}],
[['e',52] , 'AcceptabilityJudgment', {s: {html: 'He sold the t-shirt.'}}],
[['f',52] , 'AcceptabilityJudgment', {s: {html: 'He sold the apartment.'}}],
[['g',52] , 'AcceptabilityJudgment', {s: {html: 'He sold the watch.'}}],
[['h',52] , 'AcceptabilityJudgment', {s: {html: 'He sold the jewelry.'}}],
[['a',53] , 'AcceptabilityJudgment', {s: {html: 'He purchased the ring.'}}],
[['b',53] , 'AcceptabilityJudgment', {s: {html: 'He purchased the bike.'}}],
[['c',53] , 'AcceptabilityJudgment', {s: {html: 'He purchased the money.'}}],
[['d',53] , 'AcceptabilityJudgment', {s: {html: 'He purchased the key.'}}],
[['e',53] , 'AcceptabilityJudgment', {s: {html: 'He stole the ring.'}}],
[['f',53] , 'AcceptabilityJudgment', {s: {html: 'He stole the bike.'}}],
[['g',53] , 'AcceptabilityJudgment', {s: {html: 'He stole the money.'}}],
[['h',53] , 'AcceptabilityJudgment', {s: {html: 'He stole the key.'}}],
[['a',54] , 'AcceptabilityJudgment', {s: {html: 'She misplaced the document.'}}],
[['b',54] , 'AcceptabilityJudgment', {s: {html: 'She misplaced the report.'}}],
[['c',54] , 'AcceptabilityJudgment', {s: {html: 'She misplaced the paper.'}}],
[['d',54] , 'AcceptabilityJudgment', {s: {html: 'She misplaced the evidence.'}}],
[['e',54] , 'AcceptabilityJudgment', {s: {html: 'She shredded the document.'}}],
[['f',54] , 'AcceptabilityJudgment', {s: {html: 'She shredded the report.'}}],
[['g',54] , 'AcceptabilityJudgment', {s: {html: 'She shredded the paper.'}}],
[['h',54] , 'AcceptabilityJudgment', {s: {html: 'She shredded the evidence.'}}],
[['a',55] , 'AcceptabilityJudgment', {s: {html: 'She wore the jacket.'}}],
[['b',55] , 'AcceptabilityJudgment', {s: {html: 'She wore the game.'}}],
[['c',55] , 'AcceptabilityJudgment', {s: {html: 'She wore the cellphone.'}}],
[['d',55] , 'AcceptabilityJudgment', {s: {html: 'She wore the key.'}}],
[['e',55] , 'AcceptabilityJudgment', {s: {html: 'She lost the jacket.'}}],
[['f',55] , 'AcceptabilityJudgment', {s: {html: 'She lost the game.'}}],
[['g',55] , 'AcceptabilityJudgment', {s: {html: 'She lost the cellphone.'}}],
[['h',55] , 'AcceptabilityJudgment', {s: {html: 'She lost the key.'}}],
[['a',56] , 'AcceptabilityJudgment', {s: {html: 'She dropped the cookie.'}}],
[['b',56] , 'AcceptabilityJudgment', {s: {html: 'She dropped the gum.'}}],
[['c',56] , 'AcceptabilityJudgment', {s: {html: 'She dropped the candy.'}}],
[['d',56] , 'AcceptabilityJudgment', {s: {html: 'She dropped the sandwich.'}}],
[['e',56] , 'AcceptabilityJudgment', {s: {html: 'She chewed the cookie.'}}],
[['f',56] , 'AcceptabilityJudgment', {s: {html: 'She chewed the gum.'}}],
[['g',56] , 'AcceptabilityJudgment', {s: {html: 'She chewed the candy.'}}],
[['h',56] , 'AcceptabilityJudgment', {s: {html: 'She chewed the sandwich.'}}],
[['a',57] , 'AcceptabilityJudgment', {s: {html: 'He opened the window.'}}],
[['b',57] , 'AcceptabilityJudgment', {s: {html: 'He opened the arm.'}}],
[['c',57] , 'AcceptabilityJudgment', {s: {html: 'He opened the vase.'}}],
[['d',57] , 'AcceptabilityJudgment', {s: {html: 'He opened the frame.'}}],
[['e',57] , 'AcceptabilityJudgment', {s: {html: 'He broke the window.'}}],
[['f',57] , 'AcceptabilityJudgment', {s: {html: 'He broke the arm.'}}],
[['g',57] , 'AcceptabilityJudgment', {s: {html: 'He broke the vase.'}}],
[['h',57] , 'AcceptabilityJudgment', {s: {html: 'He broke the frame.'}}],
[['a',58] , 'AcceptabilityJudgment', {s: {html: 'She left the suitcase.'}}],
[['b',58] , 'AcceptabilityJudgment', {s: {html: 'She left the coat.'}}],
[['c',58] , 'AcceptabilityJudgment', {s: {html: 'She left the boot.'}}],
[['d',58] , 'AcceptabilityJudgment', {s: {html: 'She left the folder.'}}],
[['e',58] , 'AcceptabilityJudgment', {s: {html: 'She unzipped the suitcase.'}}],
[['f',58] , 'AcceptabilityJudgment', {s: {html: 'She unzipped the coat.'}}],
[['g',58] , 'AcceptabilityJudgment', {s: {html: 'She unzipped the boot.'}}],
[['h',58] , 'AcceptabilityJudgment', {s: {html: 'She unzipped the folder.'}}],
[['a',59] , 'AcceptabilityJudgment', {s: {html: 'She found the rule.'}}],
[['b',59] , 'AcceptabilityJudgment', {s: {html: 'She found the vocabulary.'}}],
[['c',59] , 'AcceptabilityJudgment', {s: {html: 'She found the formula.'}}],
[['d',59] , 'AcceptabilityJudgment', {s: {html: 'She found the equation.'}}],
[['e',59] , 'AcceptabilityJudgment', {s: {html: 'She memorized the rule.'}}],
[['f',59] , 'AcceptabilityJudgment', {s: {html: 'She memorized the vocabulary.'}}],
[['g',59] , 'AcceptabilityJudgment', {s: {html: 'She memorized the formula.'}}],
[['h',59] , 'AcceptabilityJudgment', {s: {html: 'She memorized the equation.'}}],
[['a',60] , 'AcceptabilityJudgment', {s: {html: 'She folded the handkerchief.'}}],
[['b',60] , 'AcceptabilityJudgment', {s: {html: 'She folded the car.'}}],
[['c',60] , 'AcceptabilityJudgment', {s: {html: 'She folded the hair.'}}],
[['d',60] , 'AcceptabilityJudgment', {s: {html: 'She folded the pan.'}}],
[['e',60] , 'AcceptabilityJudgment', {s: {html: 'She washed the handkerchief.'}}],
[['f',60] , 'AcceptabilityJudgment', {s: {html: 'She washed the car.'}}],
[['g',60] , 'AcceptabilityJudgment', {s: {html: 'She washed the hair.'}}],
[['h',60] , 'AcceptabilityJudgment', {s: {html: 'She washed the pan.'}}],
[['a',61] , 'AcceptabilityJudgment', {s: {html: 'She grated the cheese.'}}],
[['b',61] , 'AcceptabilityJudgment', {s: {html: 'She grated the bread.'}}],
[['c',61] , 'AcceptabilityJudgment', {s: {html: 'She grated the ham.'}}],
[['d',61] , 'AcceptabilityJudgment', {s: {html: 'She grated the pie.'}}],
[['e',61] , 'AcceptabilityJudgment', {s: {html: 'She sliced the cheese.'}}],
[['f',61] , 'AcceptabilityJudgment', {s: {html: 'She sliced the bread.'}}],
[['g',61] , 'AcceptabilityJudgment', {s: {html: 'She sliced the ham.'}}],
[['h',61] , 'AcceptabilityJudgment', {s: {html: 'She sliced the pie.'}}],
[['a',62] , 'AcceptabilityJudgment', {s: {html: 'She sipped the drink.'}}],
[['b',62] , 'AcceptabilityJudgment', {s: {html: 'She sipped the pizza.'}}],
[['c',62] , 'AcceptabilityJudgment', {s: {html: 'She sipped the taxi.'}}],
[['d',62] , 'AcceptabilityJudgment', {s: {html: 'She sipped the clothing.'}}],
[['e',62] , 'AcceptabilityJudgment', {s: {html: 'She ordered the drink.'}}],
[['f',62] , 'AcceptabilityJudgment', {s: {html: 'She ordered the pizza.'}}],
[['g',62] , 'AcceptabilityJudgment', {s: {html: 'She ordered the taxi.'}}],
[['h',62] , 'AcceptabilityJudgment', {s: {html: 'She ordered the clothing.'}}],
[['a',63] , 'AcceptabilityJudgment', {s: {html: 'He deleted the account.'}}],
[['b',63] , 'AcceptabilityJudgment', {s: {html: 'He deleted the entrance.'}}],
[['c',63] , 'AcceptabilityJudgment', {s: {html: 'He deleted the elevator.'}}],
[['d',63] , 'AcceptabilityJudgment', {s: {html: 'He deleted the safe.'}}],
[['e',63] , 'AcceptabilityJudgment', {s: {html: 'He accessed the account.'}}],
[['f',63] , 'AcceptabilityJudgment', {s: {html: 'He accessed the entrance.'}}],
[['g',63] , 'AcceptabilityJudgment', {s: {html: 'He accessed the elevator.'}}],
[['h',63] , 'AcceptabilityJudgment', {s: {html: 'He accessed the safe.'}}],
[['a',64] , 'AcceptabilityJudgment', {s: {html: 'She ironed the suit.'}}],
[['b',64] , 'AcceptabilityJudgment', {s: {html: 'She ironed the studio.'}}],
[['c',64] , 'AcceptabilityJudgment', {s: {html: 'She ironed the equipment.'}}],
[['d',64] , 'AcceptabilityJudgment', {s: {html: 'She ironed the suite.'}}],
[['e',64] , 'AcceptabilityJudgment', {s: {html: 'She rented the suit.'}}],
[['f',64] , 'AcceptabilityJudgment', {s: {html: 'She rented the studio.'}}],
[['g',64] , 'AcceptabilityJudgment', {s: {html: 'She rented the equipment.'}}],
[['h',64] , 'AcceptabilityJudgment', {s: {html: 'She rented the suite.'}}],
[['a',65] , 'AcceptabilityJudgment', {s: {html: 'She published the novel.'}}],
[['b',65] , 'AcceptabilityJudgment', {s: {html: 'She published the trip.'}}],
[['c',65] , 'AcceptabilityJudgment', {s: {html: 'She published the holiday.'}}],
[['d',65] , 'AcceptabilityJudgment', {s: {html: 'She published the meeting.'}}],
[['e',65] , 'AcceptabilityJudgment', {s: {html: 'She planned the novel.'}}],
[['f',65] , 'AcceptabilityJudgment', {s: {html: 'She planned the trip.'}}],
[['g',65] , 'AcceptabilityJudgment', {s: {html: 'She planned the holiday.'}}],
[['h',65] , 'AcceptabilityJudgment', {s: {html: 'She planned the meeting.'}}],
[['a',66] , 'AcceptabilityJudgment', {s: {html: 'He beat the rug.'}}],
[['b',66] , 'AcceptabilityJudgment', {s: {html: 'He beat the basket.'}}],
[['c',66] , 'AcceptabilityJudgment', {s: {html: 'He beat the hammock.'}}],
[['d',66] , 'AcceptabilityJudgment', {s: {html: 'He beat the web.'}}],
[['e',66] , 'AcceptabilityJudgment', {s: {html: 'He weaved the rug.'}}],
[['f',66] , 'AcceptabilityJudgment', {s: {html: 'He weaved the basket.'}}],
[['g',66] , 'AcceptabilityJudgment', {s: {html: 'He weaved the hammock.'}}],
[['h',66] , 'AcceptabilityJudgment', {s: {html: 'He weaved the web.'}}],
[['a',67] , 'AcceptabilityJudgment', {s: {html: 'He heard the compliment.'}}],
[['b',67] , 'AcceptabilityJudgment', {s: {html: 'He heard the letter.'}}],
[['c',67] , 'AcceptabilityJudgment', {s: {html: 'He heard the package.'}}],
[['d',67] , 'AcceptabilityJudgment', {s: {html: 'He heard the award.'}}],
[['e',67] , 'AcceptabilityJudgment', {s: {html: 'He received the compliment.'}}],
[['f',67] , 'AcceptabilityJudgment', {s: {html: 'He received the letter.'}}],
[['g',67] , 'AcceptabilityJudgment', {s: {html: 'He received the package.'}}],
[['h',67] , 'AcceptabilityJudgment', {s: {html: 'He received the award.'}}],
[['a',68] , 'AcceptabilityJudgment', {s: {html: 'She rehearsed the part.'}}],
[['b',68] , 'AcceptabilityJudgment', {s: {html: 'She rehearsed the offer.'}}],
[['c',68] , 'AcceptabilityJudgment', {s: {html: 'She rehearsed the gift.'}}],
[['d',68] , 'AcceptabilityJudgment', {s: {html: 'She rehearsed the donation.'}}],
[['e',68] , 'AcceptabilityJudgment', {s: {html: 'She refused the part.'}}],
[['f',68] , 'AcceptabilityJudgment', {s: {html: 'She refused the offer.'}}],
[['g',68] , 'AcceptabilityJudgment', {s: {html: 'She refused the gift.'}}],
[['h',68] , 'AcceptabilityJudgment', {s: {html: 'She refused the donation.'}}],
[['a',69] , 'AcceptabilityJudgment', {s: {html: 'She sterilized the syringe.'}}],
[['b',69] , 'AcceptabilityJudgment', {s: {html: 'She sterilized the bottle.'}}],
[['c',69] , 'AcceptabilityJudgment', {s: {html: 'She sterilized the container.'}}],
[['d',69] , 'AcceptabilityJudgment', {s: {html: 'She sterilized the lunchbox.'}}],
[['e',69] , 'AcceptabilityJudgment', {s: {html: 'She filled the syringe.'}}],
[['f',69] , 'AcceptabilityJudgment', {s: {html: 'She filled the bottle.'}}],
[['g',69] , 'AcceptabilityJudgment', {s: {html: 'She filled the container.'}}],
[['h',69] , 'AcceptabilityJudgment', {s: {html: 'She filled the lunchbox.'}}],
[['a',70] , 'AcceptabilityJudgment', {s: {html: 'He landed the plane.'}}],
[['b',70] , 'AcceptabilityJudgment', {s: {html: 'He landed the car.'}}],
[['c',70] , 'AcceptabilityJudgment', {s: {html: 'He landed the truck.'}}],
[['d',70] , 'AcceptabilityJudgment', {s: {html: 'He landed the motorcycle.'}}],
[['e',70] , 'AcceptabilityJudgment', {s: {html: 'He crashed the plane.'}}],
[['f',70] , 'AcceptabilityJudgment', {s: {html: 'He crashed the car.'}}],
[['g',70] , 'AcceptabilityJudgment', {s: {html: 'He crashed the truck.'}}],
[['h',70] , 'AcceptabilityJudgment', {s: {html: 'He crashed the motorcycle.'}}],
[['a',71] , 'AcceptabilityJudgment', {s: {html: 'He peeled the apple.'}}],
[['b',71] , 'AcceptabilityJudgment', {s: {html: 'He peeled the bowl.'}}],
[['c',71] , 'AcceptabilityJudgment', {s: {html: 'He peeled the toothbrush.'}}],
[['d',71] , 'AcceptabilityJudgment', {s: {html: 'He peeled the plate.'}}],
[['e',71] , 'AcceptabilityJudgment', {s: {html: 'He rinsed the apple.'}}],
[['f',71] , 'AcceptabilityJudgment', {s: {html: 'He rinsed the bowl.'}}],
[['g',71] , 'AcceptabilityJudgment', {s: {html: 'He rinsed the toothbrush.'}}],
[['h',71] , 'AcceptabilityJudgment', {s: {html: 'He rinsed the plate.'}}],
[['a',72] , 'AcceptabilityJudgment', {s: {html: 'She directed the movie.'}}],
[['b',72] , 'AcceptabilityJudgment', {s: {html: 'She directed the goods.'}}],
[['c',72] , 'AcceptabilityJudgment', {s: {html: 'She directed the report.'}}],
[['d',72] , 'AcceptabilityJudgment', {s: {html: 'She directed the harvest.'}}],
[['e',72] , 'AcceptabilityJudgment', {s: {html: 'She produced the movie.'}}],
[['f',72] , 'AcceptabilityJudgment', {s: {html: 'She produced the goods.'}}],
[['g',72] , 'AcceptabilityJudgment', {s: {html: 'She produced the report.'}}],
[['h',72] , 'AcceptabilityJudgment', {s: {html: 'She produced the harvest.'}}],
[['a',73] , 'AcceptabilityJudgment', {s: {html: 'He restarted the computer.'}}],
[['b',73] , 'AcceptabilityJudgment', {s: {html: 'He restarted the ball.'}}],
[['c',73] , 'AcceptabilityJudgment', {s: {html: 'He restarted the door.'}}],
[['d',73] , 'AcceptabilityJudgment', {s: {html: 'He restarted the bucket.'}}],
[['e',73] , 'AcceptabilityJudgment', {s: {html: 'He kicked the computer.'}}],
[['f',73] , 'AcceptabilityJudgment', {s: {html: 'He kicked the ball.'}}],
[['g',73] , 'AcceptabilityJudgment', {s: {html: 'He kicked the door.'}}],
[['h',73] , 'AcceptabilityJudgment', {s: {html: 'He kicked the bucket.'}}],
[['a',74] , 'AcceptabilityJudgment', {s: {html: 'She founded the newspaper.'}}],
[['b',74] , 'AcceptabilityJudgment', {s: {html: 'She founded the journal.'}}],
[['c',74] , 'AcceptabilityJudgment', {s: {html: 'She founded the biography.'}}],
[['d',74] , 'AcceptabilityJudgment', {s: {html: 'She founded the textbook.'}}],
[['e',74] , 'AcceptabilityJudgment', {s: {html: 'She read the newspaper.'}}],
[['f',74] , 'AcceptabilityJudgment', {s: {html: 'She read the journal.'}}],
[['g',74] , 'AcceptabilityJudgment', {s: {html: 'She read the biography.'}}],
[['h',74] , 'AcceptabilityJudgment', {s: {html: 'She read the textbook.'}}],
[['a',75] , 'AcceptabilityJudgment', {s: {html: 'He got the mortgage.'}}],
[['b',75] , 'AcceptabilityJudgment', {s: {html: 'He got the bill.'}}],
[['c',75] , 'AcceptabilityJudgment', {s: {html: 'He got the delivery.'}}],
[['d',75] , 'AcceptabilityJudgment', {s: {html: 'He got the shopping.'}}],
[['e',75] , 'AcceptabilityJudgment', {s: {html: 'He paid the mortgage.'}}],
[['f',75] , 'AcceptabilityJudgment', {s: {html: 'He paid the bill.'}}],
[['g',75] , 'AcceptabilityJudgment', {s: {html: 'He paid the delivery.'}}],
[['h',75] , 'AcceptabilityJudgment', {s: {html: 'He paid the shopping.'}}],
[['a',76] , 'AcceptabilityJudgment', {s: {html: 'She packed the bag.'}}],
[['b',76] , 'AcceptabilityJudgment', {s: {html: 'She packed the handle.'}}],
[['c',76] , 'AcceptabilityJudgment', {s: {html: 'She packed the trigger.'}}],
[['d',76] , 'AcceptabilityJudgment', {s: {html: 'She packed the handcart.'}}],
[['e',76] , 'AcceptabilityJudgment', {s: {html: 'She pulled the bag.'}}],
[['f',76] , 'AcceptabilityJudgment', {s: {html: 'She pulled the handle.'}}],
[['g',76] , 'AcceptabilityJudgment', {s: {html: 'She pulled the trigger.'}}],
[['h',76] , 'AcceptabilityJudgment', {s: {html: 'She pulled the handcart.'}}],
[['a',77] , 'AcceptabilityJudgment', {s: {html: 'She kept the apartment.'}}],
[['b',77] , 'AcceptabilityJudgment', {s: {html: 'She kept the house.'}}],
[['c',77] , 'AcceptabilityJudgment', {s: {html: 'She kept the oldtimer.'}}],
[['d',77] , 'AcceptabilityJudgment', {s: {html: 'She kept the boat.'}}],
[['e',77] , 'AcceptabilityJudgment', {s: {html: 'She owned the apartment.'}}],
[['f',77] , 'AcceptabilityJudgment', {s: {html: 'She owned the house.'}}],
[['g',77] , 'AcceptabilityJudgment', {s: {html: 'She owned the oldtimer.'}}],
[['h',77] , 'AcceptabilityJudgment', {s: {html: 'She owned the boat.'}}],
[['a',78] , 'AcceptabilityJudgment', {s: {html: 'She admired the tree.'}}],
[['b',78] , 'AcceptabilityJudgment', {s: {html: 'She admired the table.'}}],
[['c',78] , 'AcceptabilityJudgment', {s: {html: 'She admired the wall.'}}],
[['d',78] , 'AcceptabilityJudgment', {s: {html: 'She admired the room.'}}],
[['e',78] , 'AcceptabilityJudgment', {s: {html: 'She decorated the tree.'}}],
[['f',78] , 'AcceptabilityJudgment', {s: {html: 'She decorated the table.'}}],
[['g',78] , 'AcceptabilityJudgment', {s: {html: 'She decorated the wall.'}}],
[['h',78] , 'AcceptabilityJudgment', {s: {html: 'She decorated the room.'}}],
[['a',79] , 'AcceptabilityJudgment', {s: {html: 'He spotted the necklace.'}}],
[['b',79] , 'AcceptabilityJudgment', {s: {html: 'He spotted the ring.'}}],
[['c',79] , 'AcceptabilityJudgment', {s: {html: 'He spotted the bracelet.'}}],
[['d',79] , 'AcceptabilityJudgment', {s: {html: 'He spotted the watch.'}}],
[['e',79] , 'AcceptabilityJudgment', {s: {html: 'He engraved the necklace.'}}],
[['f',79] , 'AcceptabilityJudgment', {s: {html: 'He engraved the ring.'}}],
[['g',79] , 'AcceptabilityJudgment', {s: {html: 'He engraved the bracelet.'}}],
[['h',79] , 'AcceptabilityJudgment', {s: {html: 'He engraved the watch.'}}],
[['a',80] , 'AcceptabilityJudgment', {s: {html: 'She withdrew the testimony.'}}],
[['b',80] , 'AcceptabilityJudgment', {s: {html: 'She withdrew the word.'}}],
[['c',80] , 'AcceptabilityJudgment', {s: {html: 'She withdrew the name.'}}],
[['d',80] , 'AcceptabilityJudgment', {s: {html: 'She withdrew the appointment.'}}],
[['e',80] , 'AcceptabilityJudgment', {s: {html: 'She forgot the testimony.'}}],
[['f',80] , 'AcceptabilityJudgment', {s: {html: 'She forgot the word.'}}],
[['g',80] , 'AcceptabilityJudgment', {s: {html: 'She forgot the name.'}}],
[['h',80] , 'AcceptabilityJudgment', {s: {html: 'She forgot the appointment.'}}],

//Control Items -- to check that participants are paying attention.   
      
    
[["control",81] , "AcceptabilityJudgment", {s:"Please press one."}],
[["control",82] , "AcceptabilityJudgment", {s:"Please press two."}],
[["control",83] , "AcceptabilityJudgment", {s:"Please press three."}],
[["control",84] , "AcceptabilityJudgment", {s:"Please press four."}],
[["control",85] , "AcceptabilityJudgment", {s:"Please press five."}],
[["control",86] , "AcceptabilityJudgment", {s:"Please press six."}],
[["control",87] , "AcceptabilityJudgment", {s:"Please press seven."}],


   
];